
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 16 2026 13:44:17 IST (Apr 16 2026 08:14:17 UTC)

// Verification Directory fv/upcounter_4bit 

module upcounter_4bit(clk, reset, enable, scan_en, scan_in, test_mode,
     scan_out, count);
  input clk, reset, enable, scan_en, scan_in, test_mode;
  output scan_out;
  output [3:0] count;
  wire clk, reset, enable, scan_en, scan_in, test_mode;
  wire scan_out;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_10, n_16, n_17, n_21, n_22;
  assign count[3] = scan_out;
  SDFFRHQX4 \count_reg[3] (.RN (n_10), .CK (clk), .D (n_22), .SI
       (count[2]), .SE (scan_en), .Q (scan_out));
  SDFFRHQX1 \count_reg[2] (.RN (n_10), .CK (clk), .D (n_16), .SI
       (count[1]), .SE (scan_en), .Q (count[2]));
  INVXL g87(.A (n_6), .Y (n_8));
  OAI2BB1XL g89__5107(.A0N (count[1]), .A1N (n_1), .B0 (n_3), .Y (n_7));
  OAI21XL g90__6260(.A0 (n_2), .A1 (count[2]), .B0 (n_5), .Y (n_6));
  OAI211XL g91__8428(.A0 (count[1]), .A1 (count[0]), .B0 (n_0), .C0
       (enable), .Y (n_3));
  NAND2XL g92__5526(.A (count[2]), .B (n_2), .Y (n_5));
  SDFFRHQX4 \count_reg[0] (.RN (n_10), .CK (clk), .D (n_17), .SI
       (scan_in), .SE (scan_en), .Q (count[0]));
  INVXL g93(.A (n_0), .Y (n_2));
  NAND2XL g95__6783(.A (count[0]), .B (count[1]), .Y (n_0));
  INVXL g96(.A (reset), .Y (n_10));
  INVXL g97(.A (enable), .Y (n_1));
  SDFFRHQX1 \count_reg[1] (.RN (n_10), .CK (clk), .D (n_7), .SI
       (count[0]), .SE (scan_en), .Q (count[1]));
  MX2XL g103(.A (count[2]), .B (n_8), .S0 (enable), .Y (n_16));
  MX2XL g104(.A (enable), .B (n_1), .S0 (count[0]), .Y (n_17));
  XNOR2XL g105(.A (n_21), .B (scan_out), .Y (n_22));
  NAND2BXL g3(.AN (n_5), .B (enable), .Y (n_21));
endmodule

